### ISSUE TITLE
Install on MacOS

### ISSUE THREAD

**Issue by ksandom** [ksandom/handWavey#1]
## Tasks

- [ ] Check if the [build automation ticket](https://github.com/ksandom/handWavey/issues/8) has been done. Because that may affect how this ticket is done.
- [ ] Automate as much of the installation as possible in a macOS way.
  - For now, don't include external libraries in the handWavey repo.
  - Packaging?
  - Auto-start on login.
- [ ] Improve the [documentation for how to make it run](https://github.com/ksandom/handWavey/blob/main/README.md) on MacOS.
- [ ] Improve [the documentation for how to install it on MacOS](https://github.com/ksandom/handWavey/blob/main/docs/user/install/installOnMacOS.md).

## Background

All of the ground work is done, and it should work.

I suggest proceeding like this:
1. Get `./gradlew test` running.
2. Get `./gradlew run` running. 
  * You should be able to move the cursor around and click etc 
  * There should be no errors around being able to load and save config.
    * Note that it will tell you about writing the files for the first time on the first run. On subsequent runs, it should just tell you that it's loading, and saving the config files.
3. Begin the tasks of this ticket.

**Comment by ksandom** [comment]
MacOS has just been updated from 2.3.1 to [5.14.0](https://leap2.ultraleap.com/gemini-downloads/).

If Java support is there, then all we're waiting on is Linux support, then I can update the dependencies. I'll put more time into this when Linux support gets updated. (Windows has been kept up-to-date all along, so it's already ready.)
