### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by ksandom** [ksandom/handWavey#2]
## Tasks

- [ ] Check if the [build automation ticket](https://github.com/ksandom/handWavey/issues/8) has been done. Because that may affect how this ticket is done.
- [ ] Automate as much of the installation as possible in a Windows way.
  - For now, don't include external libraries in the handWavey repo.
  - Packaging?
  - Auto-start on login.
- [ ] Improve the [documentation for how to make it run](https://github.com/ksandom/handWavey/blob/main/README.md) on Windows.
- [ ] Improve [the documentation for how to install it on Windows](https://github.com/ksandom/handWavey/blob/main/docs/user/install/installOnWindows.md).
- [ ] Comment about which Windows versions this has been tested on.

## Goals

* Make it as easy as possible for a wide audience to be able to install.
* Where ever possible, reduce the number of steps required to do the install.

## Background

All of the ground work is done, and it should work.

I suggest proceeding like this:
1. Get `gradlew.bat test` running.
2. Get `gradlew.bat run` running. 
  * You should be able to move the cursor around and click etc 
  * There should be no errors around being able to load and save config.
    * Note that it will tell you about writing the files for the first time on the first run. On subsequent runs, it should just tell you that it's loading, and saving the config files.
3. Begin the tasks of this ticket.
