### ISSUE TITLE
Bug: Occasional segfault

### ISSUE THREAD

**Issue by ksandom** [ksandom/handWavey#6]
## Tasks

- [ ] Answer: Can the cause be determined?
- [ ] Answer: Can it be fixed on the handWavey side?
- [ ] Fix it if possible.

## Details

* When
  * 1-5 times a day under heavy usage. Once every 1-3 days under light usage.
  * Mostly random, but fails more often a few minutes after the morning resume.
  * It happens more often with more use. Ie if it's idle, it doesn't happen as much.
* Linux (OpenSuSE Tumbleweed.)
* OpenJDK /usr/lib64/jvm/java-17-openjdk-17/bin/java

## Background

Java segfaults occasionally causing handWavey to exit. It can be started back up straight away. My interpretation of the output is that the failure is happening upstream. But it's entirely possible that I'm doing something stupid that leads to the failure.

~I'll post the output when it next happens.~ - Done.

Help digging in to this would be very much appreciated.
