### ISSUE TITLE
Build handWavey in a more "Java" way

### ISSUE THREAD

**Issue by ksandom** [ksandom/handWavey#8]
## Task

- [ ] Automate building handWavey in a more Java way.
- [ ] Once installed, it can still access resources like the `.wav` files.
- [ ] Examples should be made available after the install so that the user can apply them in a predictable way.
- [ ] Create/update a wrapper script for each:
    - [ ] [Linux](https://github.com/ksandom/handWavey/blob/main/bin/run/runHandWavey-linux.sh).
    - [ ] macOS. (Maybe this can share the linux one?)
    - [ ] [Windows](https://github.com/ksandom/handWavey/blob/main/bin/run/runHandWavey-windows.bat).
- [ ] Update the documentation.
  - [ ] [Installation documentation](https://github.com/ksandom/handWavey/tree/main/docs/user/install).
  - [ ] Create documentation about how handWavey is built in the [developer area](https://github.com/ksandom/handWavey/tree/main/docs/developer).
- [ ] Tick the "Check if the [build automation ticket](https://github.com/ksandom/handWavey/issues/8) has been done." box on each of these tickets, when the PR(s) for this ticket has been merged.
  - [ ] #5 
  - [ ] #1 
  - [ ] #2 

## Background

Other than a small Android project several years ago, this is my first Java project in 18 years. Currently I'm using the gradlew wrapper to run handWavey. This feels wrong. I'm using it to manage the external dependencies.

Specifically, I'm running

```
./gradlew run
```

It would be nice to be able to start it with a single command without having to worry about depencencies.
